DATA CHAP_2_Q_5_DATA_1;
	INFILE '/folders/myfolders/Quiz/CHAP2_Q_5_1.txt';
	INPUT ID READ MATH GRADE;
RUN;

DATA CHAP_2_Q_5_DATA_2;
	INFILE '/folders/myfolders/Quiz/CHAP2_Q_5_2.txt';
	INPUT ID READ MATH GRADE;
RUN;

DATA CHAP_2_Q_5_DATA;
	MERGE CHAP_2_Q_5_DATA_1 CHAP_2_Q_5_DATA_2;
	BY ID;
RUN;

PROC PRINT DATA=CHAP_2_Q_5_DATA;
RUN;
