
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" 추가하고 싶은 플러그인을 아래에 나열하면 됩니다.
Plugin 'kien/ctrlp.vim'
Plugin 'bling/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'altercation/vim-colors-solarized'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

syntax enable " 문법강조 활성화
set wmnu      " Tab 자동 완성시 가능한 목록을 보여줌
set nu        " 라인수를 표시해 줍니다
set fencs=ucs-bom,utf-8,korea  " 파일을 읽을 때 encoding 순서입니다.

"if has("gui_running") " gvim만 적용
"	set guifont=D2Coding:h12
"set background=light
"`colorscheme solarized
"
"	set guioptions-=m  " 메뉴 삭제
"	set guioptions-=T  " 툴바 삭제
"	set guioptions-=r  " 스크롤 삭제
"endif	

set laststatus=2            " vim-airline 플러그인을 위해서 상태바 2줄로
let g:airline_left_sep=''   " vim-airline 상태바 왼쪽 구분자 없음
let g:airline_right_sep=''  " vim-airline 상태바 오른쪽 구분자 없음
set backspace=2
set ts=4
set shiftwidth=4
set hls
set autoindent
set nu

"Use TAB to complete when typing words, else inserts TABs as usual.
""Uses dictionary and source files to find matching words to complete.

"See help completion for source,
""Note: usual completion is on <C-n> but more trouble to press all the time.
"Never type the same word twice and maybe learn a new spellings!
""Use the Linux dictionary when spelling is in doubt.
"Window users can copy the file to their machine.

function! Tab_Or_Complete()
	if col('.')>1 && strpart( getline('.'), col('.')-2, 3 ) =~ '^\w'
		return "\<C-N>"
	else
		return "\<Tab>"
	endif
endfunction
inoremap <Tab> <C-R>=Tab_Or_Complete()<CR>
" 마지막으로 수정된 곳에 커서를 위치함
au BufReadPost *
                        \ if line("'\"") > 0 && line("'\"") <= line("$") |
                        \ exe "norm g`\"" |
                        \ endif
Plugin 'tomasiser/vim-code-dark'
colorscheme codedark
Plugin 'scrooloose/nerdtree'

